---
ID: "1f36940c-4080-4e6e-bb85-28a1d09df7e2"
Parent: "b2babc37-213e-45c7-b8d9-08b58d98a186"
Template: "318d7ff8-7659-4821-b442-4129f4d3a019"
Path: /sitecore/content/Blog/Home/Settings/GlobalSettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0cff296e-ebda-49ed-9f81-27a7b05b0f45"
      Hint: SubHeading
      Value: |
        <a rel="noopener noreferrer" href="https://jss.sitecore.com/" class="text-light" target="_blank" title="Sitecore">Sitecore</a> promises to be the way of the future.
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T150929Z
