---
ID: "d8116ef3-05cd-449a-831f-647aff90d188"
Parent: "318d7ff8-7659-4821-b442-4129f4d3a019"
Template: "318d7ff8-7659-4821-b442-4129f4d3a019"
Path: /sitecore/templates/Blog/Settings/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/32x32/disks.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0c8acbcd-f32c-445f-8913-27e148ab07ac"
      Hint: Heading
      Value: Sitecore Powered Blog
    - ID: "0cff296e-ebda-49ed-9f81-27a7b05b0f45"
      Hint: SubHeading
      Value: Blog powered by Sitecore
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T133338Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "bea61a36-d9ef-448d-a483-d7591e0a8201"
      Hint: Logo
      Value: |
        <image mediaid="{96493FC1-1271-48C4-B06B-046DDB922BC8}" />
    - ID: "dcd8fb28-fb64-45c2-8ee9-e4c04b5118c6"
      Hint: Copyright
      Value: Copyright @ 2023
